### ISSUE TITLE
Drop all_langs.php, use CLDR

### ISSUE THREAD

**Issue by nemobis** [B-Translator/btr_server#20]
https://github.com/B-Translator/btr_server/blob/master/modules/custom/btrCore/lib/fn/languages/all_langs.php is a very bad idea, use CLDR data instead. http://cldr.unicode.org/

CLDR is used by most i18n-heavy projects, including MediaWiki (particularly useful in https://www.mediawiki.org/wiki/Extension:Translate ).

**Comment by dashohoxha** [comment]
all_langs.php dropped (but without using CLDR).
