### ISSUE TITLE
https://btranslator.org/translations/search failure

### ISSUE THREAD

**Issue by h4ck3rm1k3** [B-Translator/btr_server#28]
looks like the url is misquoted

https://btranslator.org/translations/search%3Flng%3Dde%26origin%3Dvocabulary%26project%3DICT_de/64f8729141867d3f2634424067d38113acc70f83

×Error messageWSClientException: Error invoking the REST service <em class="placeholder">Public B-Translator Services</em>, operation <em class="placeholder">get_translations</em>: <em class="placeholder">Not Acceptable : Language missing or not supported.</em> in WSClientRESTEndpoint->call() (line 110 of /var/www/btr/profiles/btr_server/modules/contrib/wsclient/wsclient_rest/wsclient_rest.module).
The website encountered an unexpected error. Please try again later.

**Comment by dashohoxha** [comment]
How did it happen? I cannot reproduce it. Right now this url is displayed correctly:
https://btranslator.org/translations/search?lng=de&origin=vocabulary&project=ICT_de
Maybe a temporary server problem?

**Comment by h4ck3rm1k3** [comment]
it works now, 
it was from here : http://v.btranslator.org/?lng=de&proj=ICT_de#&ui-state=dialog
click on terms/list
https://btranslator.org/translations/search?lng=de&origin=vocabulary&project=ICT_de
