### ISSUE TITLE
Synchronize translations of a project with the upstream project

### ISSUE THREAD

**Issue by dashohoxha** [B-Translator/btr_server#32]

**Comment by agronselimaj** [comment]
A good reminder. Thanks.
I can do it this weekend.

//Agron

**Comment by dashohoxha** [comment]
@agronselimaj 
Right now I am experimenting with LibreOffice (synchronizing translations between B-Translator and Pootle of LibreOffice). Look at this script:
https://github.com/B-Translator/btr_server/blob/master/modules/custom/btrCore/data/sync/sq-libo_ui.sh

There is nothing yet for KDE, but I believe that it should be easier for KDE.
